version: '3'
services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - '80:80'
        volumes:
            - ./nginx/html:/etc/nginx/html:ro
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/users:/etc/nginx/users:ro
            - kumanodocs_static:/var/kumanodocs/static:ro
        links:
            - kumanodocs-hanami
            - kumanodocs
            - menu
            - bukai-issue-creator
        depends_on:
            - kumanodocs-hanami
            - kumanodocs
            - menu
            - bukai-issue-creator
        environment:
            - TZ=`ls -la /etc/localtime | cut -d/ -f8-9`

    kumanodocs-hanami:
        build: kumanodocs-hanami
        expose:
            - "2300"
        volumes:
            - ./kumanodocs-hanami:/app
            - /etc/localtime:/etc/localtime
        depends_on:
            - kumanodocs_postgres
        env_file:
            - ./kumanodocs-hanami/.env
    kumanodocs_postgres:
        image: postgres:11.3-alpine
        ports:
            - "5432:5432"
        volumes:
            - postgres_database:/var/lib/postgresql/data
        env_file:
            - ./kumanodocs-hanami/.env.pg
    kumanodocs:
        build: ./kumanodocs
        expose:
            - '8080'
        volumes:
            - ./kumanodocs:/app
            - kumanodocs_static:/var/static
            - kumanodocs_database:/var/db
        environment:
            - TZ=`ls -la /etc/localtime | cut -d/ -f8-9`
    menu:
        build: ./menu
        expose:
            - "3000"
        volumes:
            - ./menu:/app_readonly:ro
            - menu_database:/var/db
        environment:
            - TZ=`ls -la /etc/localtime | cut -d/ -f8-9`
        privileged: true # to enable mount overlay

    bukai-issue-creator:
        build: ./bukai-issue-creator
        expose:
            - "2000"
        env_file:
            - ./bukai-issue-creator/.env

    backup:
        build: ./backup
        volumes:
            - ./backup:/app
            - kumanodocs_database:/var/db/kumanodocs:ro
            - menu_database:/bar/db/menu:ro
            - backup_tmp:/var/backup
        environment:
            - TZ=`ls -la /etc/localtime | cut -d/ -f8-9`
volumes:
    postgres_database:
    kumanodocs_static:
    kumanodocs_database:
    menu_database:
    backup_tmp:
