version: '3'
services:
    nginx:
        image: nginx:alpine
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx/html:/etc/nginx/html:ro
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/users:/etc/nginx/users:ro
            - ./nginx/secrets:/etc/nginx/secrets:ro
            - kumanodocs_hanami_static:/var/kumanodocs-hanami:ro
            - ./kumanodocs-hanami/public/sw.js:/var/kumanodocs-hanami/sw.js:ro
            - kumanodocs_hanami_sock:/tmp/sockets
        links:
            - kumanodocs-hanami
            - menu
            - bukai-issue-creator
        depends_on:
            - kumanodocs-hanami
            - memo
            - menu
            - bukai-issue-creator
        environment:
            - TZ=`ls -la /etc/localtime | cut -d/ -f8-9`

    kumanodocs-hanami:
        build: kumanodocs-hanami
        expose:
            - "2300"
        volumes:
            - ./kumanodocs-hanami:/app
            - kumanodocs_hanami_static:/app/public
            - kumanodocs_hanami_sock:/tmp
            - /etc/localtime:/etc/localtime
        depends_on:
            - kumanodocs_postgres
        env_file:
            - ./kumanodocs-hanami/.env
    kumanodocs_postgres:
        image: postgres:11.3-alpine
        volumes:
            - postgres_database:/var/lib/postgresql/data
            - kumanodocs_hanami_sock:/var/run/postgresql
        env_file:
            - ./kumanodocs-hanami/.env.pg
        networks:
            backend:
                aliases:
                    - postgresdb

    memo:
        build:
            context: .
            dockerfile: hedgedoc/Dockerfile
            args:
                - "VERSION=master"
                - "HEDGEDOC_REPOSITORY=https://github.com/hedgedoc/hedgedoc.git"
        environment:
            - CMD_DB_URL=postgres://kd:kd@postgresdb:5432/hedgedoc
            - TZ=`ls -la /etc/localtime | cut -d/ -f8-9`
        expose:
            - "3000"
        networks:
            backend:
        volumes:
            - memo_uploads:/hedgedoc/public/uploads
            - kumanodocs_hanami_sock:/tmp
        restart: always
        depends_on:
            - kumanodocs_postgres

    menu:
        build: menu-sinatra
        expose:
            - "4567"
        volumes:
            - menu_database:/var/db
        environment:
            - TZ=`ls -la /etc/localtime | cut -d/ -f8-9`

    bukai-issue-creator:
        build: ./bukai-issue-creator
        expose:
            - "2000"
        env_file:
            - ./bukai-issue-creator/.env

    backup:
        build: ./backup
        volumes:
            - ./backup:/app
            - kumanodocs_hanami_sock:/tmp
            - menu_database:/bar/db/menu:ro
            - backup_tmp:/var/backup
        environment:
            - TZ=`ls -la /etc/localtime | cut -d/ -f8-9`

networks:
    backend:

volumes:
    postgres_database:
    kumanodocs_hanami_static:
    kumanodocs_hanami_sock:
    kumanodocs_database:
    memo_uploads:
    menu_database:
    backup_tmp:
