version: '2'
services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - '80:80'
        volumes:
            - ./nginx/html:/etc/nginx/html:ro
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/users:/etc/nginx/users:ro
            - kumanodocs_static:/var/kumanodocs/static:ro
        links:
            - kumanodocs
            - menu
    kumanodocs:
        build: ./kumanodocs
        expose:
            - '8080'
        volumes:
            - ./kumanodocs:/app
            - kumanodocs_static:/var/static
            - kumanodocs_database:/var/db
            - /etc/localtime:/etc/localtime:ro
    menu:
        build: ./menu
        expose:
            - "3000"
        volumes:
            - ./menu:/app_readonly:ro
            - /etc/localtime:/etc/localtime:ro
            - menu_database:/var/db
        privileged: true # to enable mount overlay

    backup:
        build: ./backup
        volumes:
            - ./backup:/app
            - kumanodocs_database:/var/db/kumanodocs:ro
            - menu_database:/bar/db/menu:ro
            - backup_tmp:/var/backup
            - /etc/localtime:/etc/localtime:ro
volumes:
    kumanodocs_static:
    kumanodocs_database:
    menu_database:
    backup_tmp:
